### ISSUE TITLE
Filters: Tick buttons flash

### ISSUE THREAD

**Issue by jellodiil** [razeware/emitron-iOS#362]
Might be a generic too obvious reloading issue or something? (I have no idea what I am saying)

Clicking to tick a filter makes the box and the tick flash for a moment, same for unticking.

https://drive.google.com/open?id=1bX3v5p_0oJ5Mz5_qy5M8e3AWL05SQnfM

**Comment by VegetarianZombie** [comment]
@sammyd I think this may be a focus shadow on the button. It's really suble and I don't think there's anything we can do about it outside of creating our own custom view. @sammyd, do you want to keep open?

**Comment by sammyd** [comment]
Nah—go ahead and close it @VegetarianZombie
