### ISSUE TITLE
Collection: Cutoff titles (iPhone 7 plus)

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#426]
Titles have ... on iPhone 7 plus. 

![IMG_2534](https://user-images.githubusercontent.com/5320361/75758614-a409a700-5d34-11ea-838a-4e65e905cc4f.jpg)

**Comment by byaruhaf** [comment]
This can be closed seems the issue was rectified. 
See Simulator Screen Shot - iPhone 7 Plus Below 

![Simulator Screen Shot - iPhone 7 Plus - 2020-11-21 at 02 33 49](https://user-images.githubusercontent.com/4116539/99862370-1dd31080-2ba2-11eb-9865-685b175eb63f.png)

**Comment by byaruhaf** [comment]
@luke-freeman I think this issue can be closed since it was rectified in #534


![Simulator Screen Shot - iPhone 7 Plus - 2021-04-08 at 18 32 17](https://user-images.githubusercontent.com/4116539/114056272-28185180-989a-11eb-996f-4e6830cc0d23.png)
