### ISSUE TITLE
Swiping away a playing video doesn't stop the audio

### ISSUE THREAD

**Issue by sammyd** [razeware/emitron-iOS#460]
It's possible to get multiple simultaneous audio streams playing, which is confusing at best.

### Steps to reproduce

1. Start the app
2. Go to stream a video
3. Pinch to minimize it

### Expected behavior

1. Audio should stop with video

### Actual behavior

1. Audio stream continues in the background

### Environment

* iOS Version: 13.3
* raywenderlich.com App Version: Latest
* Device: iPhone

**Comment by VegetarianZombie** [comment]
I've been looking at this issue. When the FullScreenVideoPlayerViewController is dismissed, the VideoPlaybackViewModel is set to nil. This deallocates the AVPlayer that stops playback. If you pinch to close or if there's any slow network connection, the model is eventually set to nil, but at that point, the ContentDetailView and the ChildContentListingView is back. I'm not sure exactly how @Binding is supposed to work in this example. But what is happening is a retain cycle. Essentially, the VideoPlayViewModel isn't deallocated. Thus, the audio keeps playing.

A short term fix is to stop video playback, but that will just stop the audio. There is still a memory leak. The more videos are watched, the greater the memory leak. Once the user leaves the ContentDetailView, everything is released from memory.

My hunch is we need to refactor how to model is passed to VideoPlaybackViewModel and the ChildContentView. Maybe avoid setting the model to nil and try a different approach. @sammyd Any thoughts / advice on how I should proceed?

Note: I did find a memory leak in one of the Futures. A self wasn't being weakly captured, but fixing that didn't solve the memory leak.

**Comment by sammyd** [comment]
I've taken a look at this @VegetarianZombie, and I'm not actually even able to replicate the problem. What I'm finding is that this method:

https://github.com/razeware/emitron-iOS/blob/development/Emitron/Emitron/UI/Video/FullScreenVideoPlayerViewController.swift#L101

Does exactly as intended—if the pinch actually dismisses the video then it calls `dismiss()`, which sets the binding to `nil`. Once that's been done then it seems that the audio stops.

The only way I could get the audio to continue whilst pinching was to put a breakpoint in that method. The audio continues until you run again. And once that's happened, there didn't appear to be any view model objects hanging around.

Am I doing something wrong? Were you able to get it to continue the audio once the video has been pinch-closed? What am I doing wrong?
