### ISSUE TITLE
Text styling changes while loading

### ISSUE THREAD

**Issue by CatieCatterwaul** [razeware/emitron-iOS#463]
Text style changes between small caps & not-caps when loading content on Library & My Tutorials tabs.

See it in action:

https://www.dropbox.com/s/37ohbks3pe0akva/iOS14%20-%20Text%20styling%20while%20loading%20-%20iPhone.mov?dl=0

**Comment by sammyd** [comment]
@VegetarianZombie this isn't fixed.

Download from test flight.
When library loads it looks like this:

![IMG_189F625A8817-1](https://user-images.githubusercontent.com/658798/95603957-e889bd80-0a4e-11eb-99a3-c2507151efd1.jpeg)

My Tutorials is correct whilst loading:

![IMG_61546D5FC40D-1](https://user-images.githubusercontent.com/658798/95604024-ffc8ab00-0a4e-11eb-8922-fb7bc50ca544.jpeg)


But then not when it is loaded:

![IMG_68994D2278C6-1](https://user-images.githubusercontent.com/658798/95604144-2d155900-0a4f-11eb-9bb1-3d5c71e1be77.jpeg)

**Comment by sammyd** [comment]
This seems to be fixed in the latest TestFlight builds.
