### ISSUE TITLE
Course episodes: First item in part has an extra line rendering on top

### ISSUE THREAD

**Issue by CatieCatterwaul** [razeware/emitron-iOS#465]
https://www.dropbox.com/s/nlnde885q0ht9wx/iOS14%20-%20first%20item%20in%20course%20part%20list%20-%20iPhone.png?dl=0

**Comment by sammyd** [comment]
![image](https://user-images.githubusercontent.com/658798/90493742-a1f8a080-e13a-11ea-8628-22747f026418.png)

**Comment by sammyd** [comment]
Fixed in #479
