### ISSUE TITLE
Tests failing on development

### ISSUE THREAD

**Issue by 0xTim** [razeware/emitron-iOS#467]
If you checkout the project, run the tests - they're failing on `development` - they shouldn't fail and should all pass! We should make them pass or fix the tests if they're wrong

**Comment by VegetarianZombie** [comment]
Hi @0xTim, what tests are failing? I've checked out the project today on development and all the tests have been passing. Was fix merged into development?

**Comment by 0xTim** [comment]
I think it's flaky tests or running on slow CI. If you have a look at the Actions for this repo you'll see 2/3 tests that are failing. Or any of the PRs

They also all pass on Xcode 12 but I haven't dug into it to see why

**Comment by sammyd** [comment]
FYI: in the past I've seen issues with some of the asynchronous tests (CombineExpectations). Upping the timeout has fixed them.

**Comment by sammyd** [comment]
This seems to be working again now (I set the limit to 5s). It's fails every now and again. Rerunning often helps.

Closing for now.
