### ISSUE TITLE
Strange animation when dowloading video course

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#469]
Strange animation when downloading video course

https://www.dropbox.com/s/weyyve1oz5k6psf/RPReplay_Final1597889856.mov?dl=0

### Steps to reproduce

Open the app and download a video course 

### Expected behavior

When downloading a video course the only expected animation should be the download indicator 

### Actual behavior

When downloading a video course the rows have moving animation.

### Environment

* iOS Version: 14.0 (18A5351d)
* raywenderlich.com App Version: App Store Version
* Device: iPad Pro (10.5-inch) MPHG2LLA

**Comment by 0xTim** [comment]
Closed via #548
