### ISSUE TITLE
Filters: Black bar visible at bottom

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#490]
At the bottom of the filters you can see a black bar 

![IMG_5187](https://user-images.githubusercontent.com/5320361/94522627-38d37500-0230-11eb-8415-6d8857406b9e.jpg)

### Steps to reproduce

Go the filters screen and look a the bottom of the screen

### Expected behavior

There should be no black bar it should be the same as the filter background color. 

### Actual behavior

There's a black bar

### Environment

* iOS Version: iOS 14
* raywenderlich.com App Version: 1.0.4
* Device: iPhone 11

**Comment by bladebunny** [comment]
I have a fix if you want to assign it to me - and I'll submit a PR.

**Comment by 0xTim** [comment]
Fixed in #490
