### ISSUE TITLE
Filters: Membership level and difficulty filters are confusing

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#491]
The terminology between Membership Level and Difficulty is confusing. 

I suggest adding 'Subscription' to the Membership entries eg. Professional Subscription

**Comment by 0xTim** [comment]
@sammyd I'm assuming this may need to be discussed internally if we're changing terminology? Or is this an existing subscription level?

**Comment by sammyd** [comment]
@luke-freeman was this from user feedback sessions? I don't mind adding this in—it's only confusing if you're a beginner subscriber, I think?

**Comment by luke-freeman** [comment]
@sammyd @0xTim 

Just append 'Subscription' to the two entries under Membership Level filter. If we can mention the subscription that is?

**Comment by sammyd** [comment]
Yeah—we can give it a try. If it gets rejected it can come back out again.
