### ISSUE TITLE
General: Update Illustrations

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#492]
This is a task for the design team. 

When I have time I'll send you some new illustrations to apply through out the app!

**Comment by luke-freeman** [comment]
@VegetarianZombie 

The assets for this are ready. 

Let me know what you need (SVG/PNG), light mode/dark mode version and and I'll export everythign and add it here. 

https://www.figma.com/file/vSA54X1aSutBqewUoLblAq/492-%E2%80%94-Update-Illustrations?node-id=0%3A1

**Comment by byaruhaf** [comment]
@luke-freeman These look awesome. 😎

**Comment by VegetarianZombie** [comment]
Hi @luke-freeman - looks great. I'm ready to integrate them into the app. Feel free to export! Cheers!

**Comment by VegetarianZombie** [comment]
Hi @luke-freeman - any word on the export timing?

**Comment by luke-freeman** [comment]
@VegetarianZombie 

What do you need exactly?

One version for light mode and one for dark mode. Also should they be in SVG?

**Comment by luke-freeman** [comment]
@luke-freeman 

From Brian: @2x and @3x and light/dark mode variations

**Comment by luke-freeman** [comment]
@VegetarianZombie 

Let me know how this works for you!

https://www.dropbox.com/sh/hqwsttykxh4bjku/AADHVty2uhQkOst6RKUO6Mwia?dl=0
