### ISSUE TITLE
Settings: Software licenses can be moved to iOS settings screen

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#496]
This was a recommendation from another iOS developer during testing. 

He suggested using 'iOS Settings bundle' to move the software licenses out of the app and into the iOS settings screens

**Comment by sammyd** [comment]
I don't think I agree with this. The idea isn't to hide the fact that we use 3rd party tools. We appreciate that there are 3rd party tools that help us build what we want to build. Moving to the settings screen feels like we want to hide stuff.

**Comment by 0xTim** [comment]
I concur - additionally I believe that some GPL licences require it to be shown in the application that bundles the code (IANAL however)

**Comment by sammyd** [comment]
Gonna close this then. Thanks @0xTim.
