### ISSUE TITLE
Settings: Black bar visible at bottom 

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#497]
Different background color bar at the bottom of the settings screen. 

![IMG_5185](https://user-images.githubusercontent.com/5320361/94523662-d1b6c000-0231-11eb-93f8-4a845a4d4253.jpg)

This should be the same color as the settings background.

**Comment by 0xTim** [comment]
This is a feature of the pop-over view in iOS - will need some investigation to see if it's actually possible

**Comment by 0xTim** [comment]
Closed in #499
