### ISSUE TITLE
Filters: Change filter show/hide design

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#498]
Many users commented on the show/hide design of filters as confusing during testing. 

It seems the show/hide with brackets is interpreted as you're choosing that many options to show or hide. Eg. Show(2) means you want to show two filters. In fact you have 2 filters applied and you need to click show to see the available filter list. 

Instead I suggest creating this: 

Move the bracketd number to the left hand side eg. Platforms · 2
Change show/hide for an chevron/arrow that changes vertically to indicate if the filters are open or closed 

Design: 

![Filters](https://user-images.githubusercontent.com/5320361/94525006-b056d380-0233-11eb-843d-4c1c8f6f130c.png)

https://www.figma.com/file/5JbVhe4SVVq89b7HGFzyWV/Library-Filters-iOS?node-id=0%3A1

**Comment by VegetarianZombie** [comment]
Hi @luke-freeman, reviewing the design, I noticed that you included a design for the Chevrons. Apple includes Chevrons as part of their SF Symbols package (https://github.com/cyanzhong/sf-symbols-online). I was planning on using chevron.up and chevron.down in SF Symbols. I do have the option of creating a custom chevron with your design. Which would you prefer I use?

Thanks!

**Comment by sammyd** [comment]
@VegetarianZombie Luke's not around this week, but he'll want you to use SF Symbols. In fact, I think I remember him asking me for exports of these chevrons so that he could make the design.

**Comment by VegetarianZombie** [comment]
Thanks @sammyd! I submitted the PR using SF Symbols as a default so it should be ready to review.
