### ISSUE TITLE
Downloaded Video Deleted After App is restarted

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#506]
When I download videos using the app and restart the app the Downloaded videos are deleted. 

### Steps to reproduce
Download any course 
Restart App
Check the download section, your downloaded videos are missing. 

### Expected behavior
downloaded should remain until the user deletes them 

### Actual behavior
Videos are deleted.

### Environment

* iOS Version: 14.1 
* raywenderlich.com App Version: 1.0.5
* Device: IPAD

* iOS Version: 14.1 
* raywenderlich.com App Version: 1.0.5
* Device: Iphone 11 

### Recording
[![](http://img.youtube.com/vi/oq5919Ev-Ts/0.jpg)](http://www.youtube.com/watch?v=oq5919Ev-Ts "")

**Comment by nesimtunc** [comment]
I also had that problem for two times, I thought first time, maybe I remember wrong, but later tried again and ensure that happened. It's gone.

**Comment by 0xTim** [comment]
Closed in #531
