### ISSUE TITLE
Chromecast feature

### ISSUE THREAD

**Issue by nesimtunc** [razeware/emitron-iOS#509]
It would be great to have Chromecast feature.

**Comment by 0xTim** [comment]
Chromecast would be cool but will require some backend work as well. With AirPlay, the device streams the video content to your Apple TV. With Chromecast you queue up a stream on the Chromecast device and the Chromecast device streams it from your backend site. So definitely possible, but making it work with the protected streams will require some work

**Comment by sammyd** [comment]
I have a feeling that it already works via the Android app.

We don't actually have protected streams available (from Vimeo). We limit access to the URL—which although far from ideal, is deemed as acceptable risk for now.

**Comment by nesimtunc** [comment]
I have neither an Android device nor Apple TV. 

Well, about 2 years ago I developed a custom Chromecast receiver web client for a protected (DRM) stream, as well Android client. On both side communication wasn't big deal, the challenging part was managing the Chromecast states on mobile side.

I don't think the development is the issue for you guys, however if you don't have time is also understandable, and since it's open source application; I might contribute for the both side if I have enough time. But, I guess the really issue is that your content provider doesn't support DRM so you don't want to risk it to open it.

**Comment by VegetarianZombie** [comment]
@sammyd @0xTim We also have the ability to incorporate the Cast framework into the app. You can see it here: https://developers.google.com/cast/docs/ios_sender

It adds another dependency, requires an API key, and will require some design work. The overview video showed the SDK using Objective-C. Oh, we'd also need to add additional privacy categories on the app store page.

That said, it doesn't seem too hard to implement. Is this something we want to do?

**Comment by 0xTim** [comment]
With the current installation steps and lack of SwiftPM support I'd be against adding this as it will add a lot of complexity to the build setup and potential confusion for readers when looking at the app

**Comment by sammyd** [comment]
I agree with Tim. Feel free to close this, or just put it on ice until the set up is a lot cleaner.

**Comment by VegetarianZombie** [comment]
Closing for now.
