### ISSUE TITLE
Global: Light Mode Style Updates

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#511]
Update the light mode version of the app to match the website. 

- Remove all instances of the grey background
- Add drop shadow to cards and search box
- Adjust drop shadow of the bottom navigation

It should look similar to this: 

<img width="375" alt="Library (Light Mode)" src="https://user-images.githubusercontent.com/5320361/97882534-07b0fd80-1d24-11eb-90e5-6652bfcbc476.png">

You can find full designs for light mode here

https://www.figma.com/file/LCwFKA0AmG9EcOQPBamGAb/Emitron-iOS?node-id=0%3A2533

**Comment by bladebunny** [comment]
I'm willing to work on this but can't access the Figma file.  I assume it has the specific styles (e.g. size and colors) I would need.

**Comment by sammyd** [comment]
@luke-freeman could you take a look at giving @bladebunny access to the Figma file please, and providing any additional direction.

@bladebunny when working on UI tickets, please attach some screenshots of the end result to the PR and ask both @0xTim and @luke-freeman to review to make sure that the designs match what Luke envisaged.

Thanks so much for offering to take this on!

**Comment by bladebunny** [comment]
@sammyd Will do.  Will add some screenshots in a few.

**Comment by luke-freeman** [comment]
@bladebunny @sammyd 

Lost the design when converting from Sketch to Figma. I'll create a new one soon

**Comment by sammyd** [comment]
🔔 @luke-freeman

**Comment by luke-freeman** [comment]
@VegetarianZombie 

I've set a task to create the designs for this. Hopefull in the next 2 weeks

**Comment by luke-freeman** [comment]
@VegetarianZombie 

This is now available https://www.figma.com/file/L2sd1y9u715iuKxotJ0GGt/Emitron-iOS?node-id=0%3A2282

let me knwo if you need any additional designs/screens. 

The main change from the old design is the removal of the grey background and adding a drop shadow to the UI elements

**Comment by VegetarianZombie** [comment]
@VegetarianZombie Okay, I'm working on implementing this.

**Comment by VegetarianZombie** [comment]
PR Submitted
