### ISSUE TITLE
Downloads: Black bar after downloaded course's

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#513]
There is a Black bar after downloaded course's

![image](https://user-images.githubusercontent.com/4116539/97989932-e9acd100-1de7-11eb-886b-ea23d0cd3a46.png)

### Steps to reproduce

Download any video course's and switch to downloads tab 

### Expected Design 

This should be the same color as the background.

### Environment

* iOS Version: 14.1
* raywenderlich.com App Version: 1.0.5
* Device: IPAD

* iOS Version: 14.1
* raywenderlich.com App Version: 1.0.5
* Device: Iphone 11

**Comment by 0xTim** [comment]
Closed in #514
