### ISSUE TITLE
Course Homepage: Title line height too loose

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#516]
Line height of titles is too loose (too much) and the titles don't look as good as they should

### Expected behavior

<img width="333" alt="Screenshot 2020-11-06 at 10 52 35" src="https://user-images.githubusercontent.com/5320361/98352447-4eea0780-201e-11eb-9eb3-fb0297c79826.png">

### Actual behavior

<img width="366" alt="Screenshot 2020-11-06 at 10 51 33" src="https://user-images.githubusercontent.com/5320361/98352471-55787f00-201e-11eb-89ad-cc0f3f45c2fd.png">

**Comment by sammyd** [comment]
Fixed
