### ISSUE TITLE
Course Homepage: Text vertical spacing (margins)

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#517]
The items like platform, title and date have too much vertical space (margins )between them.

This needs to be reduced to improve the visual design. 

### Expected behavior

<img width="351" alt="Screenshot 2020-11-06 at 10 56 15" src="https://user-images.githubusercontent.com/5320361/98352878-e0f21000-201e-11eb-98ae-8149fc825213.png">

### Actual behavior

<img width="332" alt="Screenshot 2020-11-06 at 10 56 10" src="https://user-images.githubusercontent.com/5320361/98352909-e9e2e180-201e-11eb-8fcf-6aab81c3d214.png">

**Comment by 0xTim** [comment]
Closed via #548

**Comment by luke-freeman** [comment]
@byaruhaf @0xTim 

This still isn't right. I'm not sure the design relates 100% to the code so I can't give you exact specs but the title shouldn't be that close to the lower metadata (it needs a few pixels of space). i think the space from the top of the title to the platform information should match the space from the bottom of the title to the Date etc. And if possible reduce the line height of the title text (Your First Kotlin Android App) as it seems to have too much space between each line. 

Ping me if you need more information. it might be a case of making small tweaks and reviewing each screenshot. 

![image_123986672(19)](https://user-images.githubusercontent.com/5320361/102467736-ef394000-4050-11eb-8002-b5c6abbe9ad1.JPG)

**Comment by luke-freeman** [comment]
@0xTim 

Can someone pick this up?

**Comment by byaruhaf** [comment]
Hi @luke-freeman 

 Added  Spacer() so the space from the top of the title to the platform information should match the space from the bottom of the title to the Date.

Please check the spacing below. 

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-07 at 04 24 18](https://user-images.githubusercontent.com/4116539/113797159-635f3700-9759-11eb-984f-a50420d6931d.png)

**Comment by luke-freeman** [comment]
@byaruhaf 

I think this will do! Close it :)

**Comment by byaruhaf** [comment]
Thanks @luke-freeman sending the PR now.

**Comment by sammyd** [comment]
Fixed
