### ISSUE TITLE
Library: End of list spinner

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#519]
When reaching the end of the library the loading spinner looks broken (not center with a border below it)

### Steps to reproduce

Navigate to library and scroll to end of page and wait for next results to load

### Expected behavior

The loading spinner is styled (centered and has some padding top and bottom)

### Actual behavior

Looks buggy (white background/not centered/loose border)

![image_123986672(8)](https://user-images.githubusercontent.com/5320361/98363311-0c7cf680-202f-11eb-8fdb-298cfba220f7.JPG)

### Environment

* iOS Version: 14
* raywenderlich.com App Version: 1.0.5
* Device: iPhone 11

**Comment by 0xTim** [comment]
Closed via #537
