### ISSUE TITLE
Course Homepage: Title kerning

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#520]
In the design the title has negative kerning which is equal to -0.5px. In the app the title has no kerning.

Not sure what the equivalent in Swift is to achieve this but in Figma's code output I see this: 

view.attributedText = NSMutableAttributedString(string: "What's New in Swift 5: Types", attributes: [NSAttributedString.Key.kern: -0.5, NSAttributedString.Key.paragraphStyle: paragraphStyle])

### Expected behavior

Properly kerned title text

<img width="781" alt="Screenshot 2020-11-06 at 13 04 49" src="https://user-images.githubusercontent.com/5320361/98364219-ad1fe600-2030-11eb-809b-9076bd0754cb.png">

### Actual behavior

Title text has no kerning

### Environment

* iOS Version: 14
* raywenderlich.com App Version: 1.0.5
* Device: iPhone 11

**Comment by 0xTim** [comment]
Closed via #548
