### ISSUE TITLE
Course Homepage: Description and authors vertical spacing

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#522]
There's too much white space between the description and the authors

### Expected behavior

<img width="636" alt="Screenshot 2020-11-06 at 13 15 23" src="https://user-images.githubusercontent.com/5320361/98365226-629f6900-2032-11eb-941e-d07c62cbfdda.png">

### Actual behavior

<img width="665" alt="Screenshot 2020-11-06 at 13 17 00" src="https://user-images.githubusercontent.com/5320361/98365239-67fcb380-2032-11eb-99cf-067f7388bb58.png">

### Environment

* iOS Version: 14
* raywenderlich.com App Version: 1.0.5
* Device: iPhone 11

**Comment by 0xTim** [comment]
Closed via #548
