### ISSUE TITLE
Course Homepage: Titles, subtitles and episode titles need kerning

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#523]
The title 'Course episodes', section titles of and title of each episode require kerning 

From Figma for Swift kerning

view.attributedText = NSMutableAttributedString(string: "What's New in Swift 5: Types", attributes: [NSAttributedString.Key.kern: -0.5, NSAttributedString.Key.paragraphStyle: paragraphStyle])

### Expected behavior

Kern the title, section titles and episode titles

<img width="386" alt="Screenshot 2020-11-06 at 13 22 58" src="https://user-images.githubusercontent.com/5320361/98365899-64b5f780-2033-11eb-993a-489e9c7ca87d.png">

### Actual behavior

No kerning applied

![image_123986672(11)](https://user-images.githubusercontent.com/5320361/98365886-5e278000-2033-11eb-8ff1-01acb738cbdb.JPG)

### Environment

* iOS Version: 14
* raywenderlich.com App Version: 1.0.5
* Device: iPhone 11

**Comment by 0xTim** [comment]
Closed via #548
