### ISSUE TITLE
Course Homepage: Episode list main title has random borders

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#524]
Episode list in a course homepage appears to have borders that shouldn't be there

### Steps to reproduce

Navigate to a course homepage
In this example I'm on 'Introduction to Google's Material Design'

### Expected behavior

Episode list only has borders between episodes

### Actual behavior

Episode list has border above and below main title 'Course Episodes'

![image_123986672(12)](https://user-images.githubusercontent.com/5320361/98367300-ae9fdd00-2035-11eb-9b44-d511c4775d10.JPG)

### Environment

* iOS Version: 14
* raywenderlich.com App Version: 1.0.5
* Device: iPhone 11

**Comment by byaruhaf** [comment]
This issue should be closed the issue, Design has been corrected. 

![image](https://user-images.githubusercontent.com/4116539/101275511-e45bf100-37ae-11eb-9125-e977de54e76e.png)

**Comment by 0xTim** [comment]
@luke-freeman is this now fixed?
