### ISSUE TITLE
Downloads: Black bar

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#526]
On the download page with one downloaded video course I see a huge black bar

### Steps to reproduce

Download one video course
Go to downloads tab

### Expected behavior

No black bar visible

### Actual behavior

![image_123986672(14)](https://user-images.githubusercontent.com/5320361/98369364-1d326a00-2039-11eb-924a-13530d0f5ab5.JPG)

### Environment

* iOS Version: 14
* raywenderlich.com App Version: 1.0.5
* Device: iPhone 11

**Comment by 0xTim** [comment]
Closed in #514
