### ISSUE TITLE
My Tutorials: End of list black bar

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#527]
At the end of the list of tutorials (I have a lot of entries might be different with less entries) there's a black bar

### Steps to reproduce

- Navgiate to My Tutorials tab
- In my example I have many tutorials under completed tab
- Scroll the end of list

### Expected behavior

No black bar visible

### Actual behavior

![image_123986672(15)](https://user-images.githubusercontent.com/5320361/98369819-d8f39980-2039-11eb-8fa0-f617a7ee7445.JPG)

### Environment

* iOS Version: 14
* raywenderlich.com App Version: 1.0.5
* Device: iPhone 11

**Comment by byaruhaf** [comment]
This issue should be closed the issue, Design has been corrected. 

![image](https://user-images.githubusercontent.com/4116539/101272032-2f670b80-3791-11eb-84e8-e6ef8ab632b1.png)
