### ISSUE TITLE
Replace AVPlayerViewController with SwiftUI’s VideoPlayer view

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#542]
Use the new SwiftUI’s `VideoPlayer` view instead of `AVPlayerViewController` with `UIViewControllerRepresentable` after iOS13 is dropped.

https://developer.apple.com/documentation/avkit/videoplayer

**Comment by JessyCatterwaul** [comment]
I investigated this in #653. It's very close to being worth doing. Here's hoping iOS 16 changes that for the better.
