### ISSUE TITLE
Setting Downloads(WIFI only), not working. 

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#544]
### Steps to reproduce

- Go to settings Enable Downloads(WIFI only)

- Try to downloads any video courses

### Expected behavior

The download should fail or be queued for the next time WIFI Available

### Actual behavior

The download is successful and the video plays see the video below:

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/4116539/101596932-9dfcd100-39fe-11eb-9cf0-052f5d8ad0da.gif)

### Environment

* iOS Version:14.2
* raywenderlich.com App Version: 1.0.6
* Device:iPhone 11

**Comment by VegetarianZombie** [comment]
Hi @luke-freeman, I've confirmed this bug and this is occurring. How would you like to handle it? I can present a simple iOS dialog when the user taps on a download, informing them that they can't download being on a cellular connection. Or do you want to display a custom notification?

**Comment by VegetarianZombie** [comment]
![6044](https://user-images.githubusercontent.com/973751/130517648-4d655544-e4d3-4e93-8e0c-bb454a870dfb.jpg)
