### ISSUE TITLE
Refactor from UIKit App Delegate life-cycle to SwiftUI life-cycle

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#545]
Removed AppDelegate & SceneDelegate refactor to use SwiftUI life-cycle.  After iOS13 is dropped.

**Comment by adesugbaa** [comment]
Is there a timeline for dropping iOS13 support?

**Comment by 0xTim** [comment]
@adesugbaa essentially when there's something we can't do in iOS 13 that would be good for a tutorial. We don't have a set timeline, just when it makes sense

**Comment by VegetarianZombie** [comment]
This is merged into development with PR #581. Closing the issue.
