### ISSUE TITLE
Unused Code

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#547]
I used  [Periphery](https://github.com/peripheryapp/periphery) on the project to identify unused items of code.
See log file [Unused.LOG](https://github.com/razeware/emitron-iOS/files/5664315/Unused.LOG) for results. 

I investigated a few and sent PR #546 for the ones I verified. 

For some, however, I'm not sure if they are unused because they are possible future features of the app or their functionality was refactored out. 

so I open this issue, not sure if this is something the project is interested in. 

But if yes we could start with these functions below:
Are they future App features or they can be removed? 

```zsh
DownloadProcessor.swift:44:8: warning: Function 'downloadProcessor(_:didPauseDownloadWithId:)' is unused
DownloadProcessor.swift:45:8: warning: Function 'downloadProcessor(_:didResumeDownloadWithId:)' is unused
DownloadProcessor.swift:102:8: warning: Function 'pauseDownload(_:)' is unused
DownloadProcessor.swift:110:8: warning: Function 'resumeDownload(_:)' is unused
DownloadService.swift:507:8: warning: Function 'downloadProcessor(_:didPauseDownloadWithId:)' is unused
DownloadService.swift:511:8: warning: Function 'downloadProcessor(_:didResumeDownloadWithId:)' is unused
```

**Comment by 0xTim** [comment]
I'm good for these to be removed - @sammyd ?

**Comment by sammyd** [comment]
Fine by me!

**Comment by s3627667** [comment]
did these lines end up being removed as part of #546? If so, this should be closed out. If not, this issue should be updated to avoid confusion
