### ISSUE TITLE
Course Homepage: Lesson list has different top/bottom padding

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#549]
The padding/spacing at the top of a lesson and bottom of a lesson appears to be different

<img width="707" alt="Screenshot 2020-12-17 at 10 27 43" src="https://user-images.githubusercontent.com/5320361/102469127-a7b3b380-4052-11eb-8aeb-faa18484aa38.png">

### Steps to reproduce

Go to a video course homepage and view the lesson list

### Expected behavior

The spacing should be the same

### Actual behavior

The padding/spacing at the top of a lesson and bottom of a lesson appears to be different

### Environment

* iOS Version: 14
* raywenderlich.com App Version: 1.0.6 (Beta)
* Device: iPhone 11

**Comment by byaruhaf** [comment]
Hi @luke-freeman 

Reduced the padding in the list items, please check the screenshot below 

![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-17 at 18 03 27](https://user-images.githubusercontent.com/4116539/102512469-c174eb00-4092-11eb-9fb5-0de6dcac423b.png)

**Comment by luke-freeman** [comment]
@byaruhaf 

I don't think the padding needs to be reduced. Just that it's even top and bottom. 

In the production app the padding is perfect. Can you replicate that?

![image_123986672(22)](https://user-images.githubusercontent.com/5320361/102598194-ed887e80-411b-11eb-8e14-534bb6e073c4.JPG)

**Comment by luke-freeman** [comment]
@sammyd @byaruhaf 

Where are we with this?

**Comment by byaruhaf** [comment]
Hi @luke-freeman 

I took another crack it, using a Vstack for the Download icon. Please see the image below. 
Let me know what you think. 

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-07 at 03 29 55](https://user-images.githubusercontent.com/4116539/113793725-a9180180-9751-11eb-8bf7-22da703270a0.png)

**Comment by luke-freeman** [comment]
@byaruhaf Looks very tidy thanks!

**Comment by byaruhaf** [comment]
Thanks @luke-freeman sending the PR now.

**Comment by sammyd** [comment]
Fixed
