### ISSUE TITLE
Why don’t you use URLSession.shared.dataTaskPublisher?

### ISSUE THREAD

**Issue by dadachi** [razeware/emitron-iOS#551]
Why don’t you use `URLSession.shared.dataTaskPublisher` instead of `URLSession.dataTask`?

**Comment by adesugbaa** [comment]
There are only 2 occurrences of URLSession.dataTask in the codebase.

Is there any reason why you suggest switching to URLSession.shared.dataTaskPublisher?

**Comment by 0xTim** [comment]
Just to add to this - the app is primarily a teaching aid, so it's possible there's an older course that didn't use Combine that needed a plain `dataTask` as well. This is likely to all change when async/await lands anyway

**Comment by VegetarianZombie** [comment]
Closing issue for now. We can reassess post WWDC.
