### ISSUE TITLE
Retain Filters between runs

### ISSUE THREAD

**Issue by tarasis** [razeware/emitron-iOS#552]
It would be useful if the iOS app retained the filters I set between runs of the app. I have no interest in seeing Android videos, so its irritating to have to disable it each time.

### Steps to reproduce

- Open app.
- Tap Filters button
- Change Platforms to iOS  & Swift.
- Leave app for a while
- Re-open app, filters forgotten.

### Expected behavior

I would expect the app to remember what filters I selected until I reset them myself.

### Actual behavior

It forgets the filters I had selected.

### Environment

* iOS Version: 14.4
* raywenderlich.com App Version: 1.0.6
* Device: iPad Pro 10.5"

**Comment by adesugbaa** [comment]
Do we want to retain filter settings for the user profile (across multiple devices) or on a single device?

**Comment by sammyd** [comment]
Just on a single device for now, please. We don't have the backend infrastructure to track across multiple devices yet.

**Comment by 0xTim** [comment]
Closed in #564 and #603
