### ISSUE TITLE
Swiftlint install failing on build machine

### ISSUE THREAD

**Issue by bladebunny** [razeware/emitron-iOS#562]
PR checks are failing because Swiftlint install is failing on the build machine
### Expected behavior
Swiftlint install on build pipeline should not fail

### Actual behavior
Swiftlint install on build pipeline fails

### Environment
development

n/a
* iOS Version:
* raywenderlich.com App Version:
* Device:

**Comment by sammyd** [comment]
I think this will be fixed with #557

**Comment by 0xTim** [comment]
This seems to now be fixed, all the PRs with updated branches are now working (at least for the SwiftLint phase)
