### ISSUE TITLE
If fetching permissions fails, the loading screen will continue to appear

### ISSUE THREAD

**Issue by dadachi** [razeware/emitron-iOS#567]
If fetching permissions fails, the loading screen will continue to appear.

### Steps to reproduce

- Sign out.
- Replaces permissions request path with wrong path for simulating for server side error.
https://github.com/razeware/emitron-iOS/blob/development/Emitron/Emitron/Networking/Requests/PermissionsRequest.swift#L37

### Expected behavior

Display error message.
And if the error is authentication error(HTTP status code: 401), you should display the login screen.

### Actual behavior

 The loading screen will continue to appear.

### Environment

* iOS Version: iOS14
* raywenderlich.com App Version: v1.0.6
* Device: iPhone 12 Mini Simulator

**Comment by VegetarianZombie** [comment]
Thanks. Just replicated your issue. Taking a look.

**Comment by VegetarianZombie** [comment]
Hi @luke-freeman, would you like to produce a mockup of the notification or do you want me to use a standard iOS alert notification?

**Comment by sammyd** [comment]
🔔 @luke-freeman

**Comment by luke-freeman** [comment]
@VegetarianZombie 

I've set a task to look into this. I'll try to deliever something in the next 2 weeks.

**Comment by luke-freeman** [comment]
@VegetarianZombie 

I have a very basic design for this

https://www.figma.com/file/WaYjtN0Gi2CB9L6rMYtjp5/567-%E2%80%94-Fetching-Permissions?node-id=2%3A72

Can you give me some more context on the error?

Should the user simply click a button to force their way out of this state

**Comment by JessyCatterwaul** [comment]
Hi @luke-freeman. I'm taking this one over.

Can you give my @razeware.com address permission to view that file please?

**Comment by luke-freeman** [comment]
@JessyCatterwaul 

Can you access now?

**Comment by JessyCatterwaul** [comment]
@luke-freeman I can—thanks! I'll get you more info when I understand the problem a bit more.

**Comment by JessyCatterwaul** [comment]
I've got a fix in-place, reusing this view from elsewhere in the app:

<img width="403" alt="Screen Shot 2021-08-19 at 6 37 09 PM" src="https://user-images.githubusercontent.com/8386742/130154486-a058ac96-acfd-4b4f-9300-21279eca56f0.png">

@luke-freeman, what should we be doing about the smileys? Switch the old one out for your new graphic from Figma, app-wide?

@sammyd Do we have standardized verbiage for this? "We failed to fetch the correct permissions" maybe isn't so great a user-facing statement?

**Comment by JessyCatterwaul** [comment]
@0xTim It looks like I need to be given access so I can push my branch? Or are we all just forking it?

**Comment by 0xTim** [comment]
@JessyCatterwaul I guess RW people should have access it. However I don't have permissions to give you access, that's one for @luke-freeman

**Comment by sammyd** [comment]
@JessyCatterwaul I've sent you an invite to be a maintainer of this repo. Gimme a shout if that doesn't suffice.

**Comment by luke-freeman** [comment]
@JessyCatterwaul 

For now you can use the illustraiton that's there as I have another issue to update the illustrations app wide!

**Comment by 0xTim** [comment]
Closed via #592
