### ISSUE TITLE
Subtitles missing when "Auto" option is selected

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#568]
### Steps to reproduce
Download 1 episode of a course.
Switch between three subtitle options

<img width="1685" alt="Screenshot 2021-04-21 at 21 57 32" src="https://user-images.githubusercontent.com/4116539/115606641-a50ce780-a2ec-11eb-9edc-58c3d5510920.png">

### Expected behavior
Subtitles should show if either the Auto(Recommended) or English SDH version is selected.  
Subtitles should not show when the Off option is selected.  

### Actual behavior
Subtitles only show English SDH version is selected.  
Subtitles are disabled if either the Auto(Recommended) or Off option is selected.  

Here is a video Demo:

https://user-images.githubusercontent.com/4116539/115607503-bc98a000-a2ed-11eb-889f-ce073a33cb03.mov

### Environment

* iOS Version: 14.4.2
* raywenderlich.com App Version: Dev Branch 
* Device: IPhone 11

**Comment by VegetarianZombie** [comment]
Hi @0xTim,

Any thoughts about this? I'm listening for the media mediaSelectionDidChangeNotification. In it, I've written the following code when the notification occurs:

if let playerItem = notification.object as? AVPlayerItem {
          if let subtitles = playerItem.asset.mediaSelectionGroup(forMediaCharacteristic: .legible) {
               print(playerItem.currentMediaSelection.selectedMediaOption(in: subtitles))
         }
}

This produces a nil value when the user selects the automatic subtitles. Have you encountered anything similar in your own media apps?

**Comment by 0xTim** [comment]
It might depend on what locale the user has set, it looks like AVPlayer tries to infer which language to use which may not be available?

**Comment by VegetarianZombie** [comment]
I don't really see this being issue. @0xTim, are you okay with me closing this?

**Comment by 0xTim** [comment]
Sure
