### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by mobiletrish** [razeware/emitron-iOS#577]
When trying to connect to the services I am receiving the following error:

 Optional<Error>
  - some : Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x60000380c510>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<cert(0x7feef983c200) s: api.raywenderlich.com i: Zscaler Intermediate Root CA 3>",
    "<cert(0x7feef983b600) s: Zscaler Intermediate Root CA 3 i: Enterprise Root CA 3>"
), NSUnderlyingError=0x60000048b5d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x60000380c510>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7feef983c200) s: api.raywenderlich.com i: Zscaler Intermediate Root CA 3>",
    "<cert(0x7feef983b600) s: Zscaler Intermediate Root CA 3 i: Enterprise Root CA 3>"
)}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.,

When running the openssl command, I found that the verification was failing.  The verification error came bake as "verify error:num=20:unable to get local issuer certificate".

<img width="821" alt="image" src="https://user-images.githubusercontent.com/36375848/118048177-e6bc0b80-b349-11eb-977c-514593ecec11.png">

Also, when going to chrome or safari and putting https://api.raywenderlich.com/api/domains in the URL, I am also seeing an error around making a secure connection.

### Steps to reproduce
In order to see the error, I ran the app in the simulator and put a breakpoint in the Service.swift file where the httpResponse is returned in the makeAndProcessRequest function.  

Note: I did have the root certificate installed in the simulator and the certificate trust setting was turned on when running the application.

### Expected behavior
The service calls should be made without returning an SSL error.

### Actual behavior
The data isn't downloaded from the service because it is hanging on the SSL Error.

### Environment
iOS Version: 13.4
App Version: 1.0.6
Device: iPhone 11 Pro

**Comment by byaruhaf** [comment]
Is the login process for the App Successful￼?

**Comment by 0xTim** [comment]
@mobiletrish why have you blacked out the certificate details? It looks like you're running through some proxy via Zscalar which is trying to intercept the traffic and MITM the connection with it's own certificate. So you're on a dodgy network (either accidentally via wifi that needs logging in or on something like a corporate network that is stuck in the past and _really_ should not be intercepting traffic). This is not an issue with the app

**Comment by mobiletrish** [comment]
@byaruhaf Yes, I am able to login, but before logging in I am being told the connection isn't valid.  There is a link to continue on the view that appears and allows me to continue.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/36375848/118108927-91feac00-b3ae-11eb-9db8-42ef58c2d80e.png">


@0xTim I have blacked out the certificate details because I am running this on my corporate computer.

**Comment by 0xTim** [comment]
@mobiletrish your corporate network is trying to MITM the connection which is why it's failing. Putting aside the issues with that, you need to either use a different network or trust the root certificate that's trying to resign all the certificates

**Comment by byaruhaf** [comment]
@mobiletrish change to a different network
