### ISSUE TITLE
Visible disclosure arrow indicator iOS 15

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#587]
When scrolling through the various lists on the app, the disclosure arrow indicator for the list items is shown. 
This makes the list items look squeezed from the sides. 

### Steps to reproduce
Open the app and scroll through the Library View list

### Expected behavior
The disclosure arrow indicator for SwiftUI List should be hidden

### Actual behavior
The disclosure arrow indicator for SwiftUI List should is shown

### Environment

* iOS Version: 15 beta 4
* raywenderlich.com App Version: 1.0.7
* Device: iPhone 12 Max pro

![Simulator Screen Recording - iPhone 12 Pro Max - 2021-08-16 at 09 10 05](https://user-images.githubusercontent.com/4116539/129518929-dfcfe98d-9311-4a6f-8e90-27bd73d58d26.gif)

**Comment by hqin0066** [comment]
Hi @byaruhaf, I'm on iOS 15 beta 6 now and I think the issue is gone.

**Comment by VegetarianZombie** [comment]
Hi @JessyCatterwaul, I no longer have iOS 15 installed - are you good to confirm?

**Comment by JessyCatterwaul** [comment]
On beta 7, the chevron was only gone on the first item in the list. And only in the Library tab.

As far as I know, we've gotten nothing new to help with this in this beta cycle. So I switched to a different old hack, considering the hack that Emitron was already using no longer works. 🙃

https://github.com/razeware/emitron-iOS/pull/593
