### ISSUE TITLE
Course Homepage: Weird text formatting in course description

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#588]
The text in the descrition is breaking onto new lines where it shouldn't be.

![image_123986672](https://user-images.githubusercontent.com/5320361/129711738-9969e42a-b595-40ee-86e2-b782406e56fa.JPG)

### Steps to reproduce

Check out the Integrate Combine course

### Expected behavior

Paragprahs should have complete sentences and spaces betwene paragraphs.

### Actual behavior

Paragraph text is being broken onto newlines

### Environment

* iOS Version: 14.4
* raywenderlich.com App Version: 1.0.7
* Device: iPhone 11

**Comment by VegetarianZombie** [comment]
Hi @luke-freeman, are you still seeing this? I wonder if this was an issue with the description in betamax versus an app issue. Definitely, let me know! Cheers!

**Comment by hqin0066** [comment]
Hi @VegetarianZombie @luke-freeman , I just checked on my site with iPhone X iOS 15 beta 6 and iPhone 7 plus iOS 14.7. The issue still exists for around third of the lastest videos. Will take a look into the code but I do think it's a server side problem since it's not persistent for all the videos.

**Comment by VegetarianZombie** [comment]
Thanks @hqin0066 - I've just confirmed on my phone. @sammyd I checked out the API endpoint and it appears to be stray newlines that appear causing the lines. You can definitely see it on SQLDelight in Android: Getting Started. I'm viewing on an iPhone 12. I'm guessing this looks more exaggerated on larger screens.

**Comment by sammyd** [comment]
@VegetarianZombie can you remind me what the rendered field is called? It's possible that the newlines should be ignored (as they would be in HTML). Or we can look at stripping them out in the server.

**Comment by VegetarianZombie** [comment]
Hi @sammyd, Looking at the endpoint, it appears to be found in the 'description' field found in the 'attributes' object. Note, this shows up in the 'description_plain_text' as well. I'll see what I can do stripping out the special characters and HTML.

**Comment by sammyd** [comment]
@VegetarianZombie sounds good to me. We'll try to update the API data source too at some point.
