### ISSUE TITLE
Hard Crash 

### ISSUE THREAD

**Issue by VegetarianZombie** [razeware/emitron-iOS#591]
I'm running into a hard crash using development. 

### Steps to reproduce

Start up the app. Navigate to the My Tutorials tab, select Completed or Bookmarks. Tapping each of these categories will cause the app to crash. 

* iOS Version: 14.7.1
* raywenderlich.com App Version: Development brach
* Device: iPhone 12

**Comment by VegetarianZombie** [comment]
I'm getting an exec breakpoint error but not at a particular line. Still trying to track down the location of the error.

**Comment by VegetarianZombie** [comment]
@sammyd @0xTim @JessyCatterwaul Any thoughts on this are appreciated. I'm doing a lot of wheel-spinning, ATM

**Comment by JessyCatterwaul** [comment]
@VegetarianZombie, this is where I'm at with this one 😔:

<img src="https://pbs.twimg.com/media/DS7ojjyU0AAbZnC.jpg" height="450">

I'm only using iOS 15 though. If you'd like me to try on 14, let me know, but Xcode is only giving me the option to download up to 14.5, not 14.7

**Comment by VegetarianZombie** [comment]
I think this is related to my account. I had two accounts on raywenderlich.com - and my old account appears to still work and may have tripped up the error. I'm guessing I have some corrupted state on my device. Not sure. It works sometimes. It crashes other times. 

I'll close for now unless we run into this again.
