### ISSUE TITLE
TabView is sometimes transparent when it should not be, in iOS 15

### ISSUE THREAD

**Issue by JessyCatterwaul** [razeware/emitron-iOS#598]
I can reproduce this issue approximately 70% of the time.

Dealing with it in UIKit seems easy. In SwiftUI, we don't have direct tools for it.

https://developer.apple.com/forums/thread/682432
https://www.reddit.com/r/SwiftUI/comments/p8obef/disable_new_ios_15s_transparent_tabview/

I've been looking for suspicious code, that might be confusing SwiftUI, yielding nondeterministic results. I haven't found a culprit yet.

<img src="https://user-images.githubusercontent.com/8386742/132126692-c0d556bf-e925-4b5e-a85e-ed5d0bcf47d9.PNG" height="500">
<img src="https://user-images.githubusercontent.com/8386742/132126694-8d009a8a-9d69-4530-aca8-667d12de44cd.PNG" height="500">
<img src="https://user-images.githubusercontent.com/8386742/132126697-2287edd7-b6b4-44ab-a681-4b85e20c0065.PNG" height="500">

**Comment by hqin0066** [comment]
Hi @JessyCatterwaul, I'm on iOS 15 beta 8 right now and I was not able to reproduce it. Could you please provide the way to reproduce this issue? Also, please check out this link: [http://5.9.10.113/67899805/ios-15-tab-bar-transparent-after-scrolling-to-the-bottom](url). I was able to fix a similar issue when building my own app. Thank you!
