### ISSUE TITLE
Replace custom ProgressBarView with ProgressView

### ISSUE THREAD

**Issue by riana-soumi** [razeware/emitron-iOS#606]
Use SwiftUI's ProgressView with LinearProgressViewStyle instead of custom ProgressBarView in order to simplify the code.
https://developer.apple.com/documentation/swiftui/linearprogressviewstyle

**Comment by VegetarianZombie** [comment]
Hi @ria-heikkila, am I mistaken, but wasn't this issue already merged into development, or is this something different? Cheers!
