### ISSUE TITLE
navigationBar wrong color for iOS 15.2 and higher 

### ISSUE THREAD

**Issue by byaruhaf** [razeware/emitron-iOS#642]
### Steps to reproduce
NavigationBar wrong color & font for iOS 15.2 and higher 

see image showing Expected in iOS 14.5 vs Actual in iOS15.2:

<img width="880" alt="Screenshot 2022-01-28 at 01 43 10" src="https://user-images.githubusercontent.com/4116539/151475052-f9a1aa99-cef0-4fa7-b2bf-61d0cc3528e0.png">

### Environment

* iOS Version: iOS15.2
* Device: running in the simulator PRO MAX

**Comment by JessyCatterwaul** [comment]
Thanks for catching this, @byaruhaf. It was a problem in light mode too, but it just didn't look as bad.
